# Porta HTTP
quarkus.http.port=8081

# Banco de dados H2 (modo em memória)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:appdb;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.database.generation=drop-and-create

# Desativar Flyway se não quiser migrations
# quarkus.flyway.migrate-at-start=false

# Mostrar SQL no console
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# JSON bonito
quarkus.jackson.indent-output=true



# Swagger/OpenAPI
quarkus.smallrye-openapi.info-title=Onload API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=CRUD de Clientes com Quarkus + Panache
quarkus.smallrye-openapi.servers=http://localhost:8081

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

# Segurança / JWT
mp.jwt.verify.publickey.location=classpath:jwt/publicKey.pem
mp.jwt.verify.issuer=onload-api
smallrye.jwt.sign.key.location=classpath:jwt/privateKey.pem
smallrye.jwt.new-token.signature-algorithm=RS256
security.auth.shared-secret=onload-secret
security.auth.token-expiration-seconds=3600
